### ISSUE TITLE
道具功能

### ISSUE THREAD

**Issue by Liangyu-G** [Agnes4m/CS2UID#3]
BUG？
![微信截图_20241022164517](https://github.com/user-attachments/assets/41682e83-a8fd-4d2d-bb3e-3885002b2c05)

**Comment by Liangyu-G** [comment]
另外希望可以在输入“cs道具 ‘地图名称’”之后，可以显示出这张地图的所有点位。

**Comment by Liangyu-G** [comment]
原来是需要完整的地图名称，学会了

**Comment by Agnes4m** [comment]
![image](https://github.com/user-attachments/assets/d253f934-eae9-48d5-a544-bcaadf03a6b6)

**Comment by Liangyu-G** [comment]
> ![image](https://private-user-images.githubusercontent.com/70925546/378762435-d253f934-eae9-48d5-a544-bcaadf03a6b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODg3NDYsIm5iZiI6MTcyOTU4ODQ0NiwicGF0aCI6Ii83MDkyNTU0Ni8zNzg3NjI0MzUtZDI1M2Y5MzQtZWFlOS00OGQ1LWE1NDQtYmNhYWRmMDNhNmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA5MTQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMzkxODU5NDQ3YmFhYmZlYjI0OGQ0ZTk4NTllZmUxM2MyZWQ5MjQ2N2I2NzI4NDZjOWY2NzFiZWIzZGM0MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yBGlZH72JyRCei_woQh_6PqSQNI01bPoMXAd2EXUvvA)

我只能用地图全称才有用

**Comment by Liangyu-G** [comment]
![image](https://github.com/user-attachments/assets/4572f84c-1175-495b-86ca-ddd9b727628f)

**Comment by Agnes4m** [comment]
因为我是按照空格划分判断的，正则太难了）

**Comment by Liangyu-G** [comment]
> 因为我是按照空格划分判断的，正则太难了）

![image](https://github.com/user-attachments/assets/06d27220-f632-465e-ab38-9ab696ef4be5)
学废了，写的不够清晰啊喂！！！

**Comment by Agnes4m** [comment]
双击看大图
![image](https://github.com/user-attachments/assets/1f8e4349-2b17-49e4-b5f2-0e9977d9de2b)


还有目前小镇和改后大厦的点位没有
最近忙着野牛冲锋，没时间写攻略，干拉，爽+
![image](https://github.com/user-attachments/assets/e9718b60-e1f5-4482-942a-56fe075d773d)
