### ISSUE TITLE
加载插件时发生错误

### ISSUE THREAD

**Issue by Wabits** [Agnes4m/CS2UID#5]
![c131226e-0a86-4739-a6ec-ceb1f4bac543](https://github.com/user-attachments/assets/ff7be2a7-d01d-41d0-9963-5ef57b710b06)

**Comment by Agnes4m** [comment]
没截图到底，请报错截图完整

**Comment by Wabits** [comment]
![6327faf4-768f-4dd4-9548-94916e66334e](https://github.com/user-attachments/assets/193c961b-448e-4a3e-a29e-1eb1df9a8493)

**Comment by Agnes4m** [comment]
已更新修复
